# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: humidity.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'humidity.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ehumidity.proto\"\x08\n\x06\x45mptyH\"$\n\x10HumidityResponse\x12\x10\n\x08humidity\x18\x01 \x01(\x02\x32<\n\x0fHumidityService\x12)\n\x0bGetHumidity\x12\x07.EmptyH\x1a\x11.HumidityResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'humidity_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTYH']._serialized_start=18
  _globals['_EMPTYH']._serialized_end=26
  _globals['_HUMIDITYRESPONSE']._serialized_start=28
  _globals['_HUMIDITYRESPONSE']._serialized_end=64
  _globals['_HUMIDITYSERVICE']._serialized_start=66
  _globals['_HUMIDITYSERVICE']._serialized_end=126
# @@protoc_insertion_point(module_scope)
