# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import humidity_pb2 as humidity__pb2

GRPC_GENERATED_VERSION = '1.66.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in humidity_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HumidityServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetHumidity = channel.unary_unary(
                '/HumidityService/GetHumidity',
                request_serializer=humidity__pb2.EmptyH.SerializeToString,
                response_deserializer=humidity__pb2.HumidityResponse.FromString,
                _registered_method=True)


class HumidityServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetHumidity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HumidityServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetHumidity': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHumidity,
                    request_deserializer=humidity__pb2.EmptyH.FromString,
                    response_serializer=humidity__pb2.HumidityResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'HumidityService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('HumidityService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HumidityService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetHumidity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/HumidityService/GetHumidity',
            humidity__pb2.EmptyH.SerializeToString,
            humidity__pb2.HumidityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
