# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: temperature.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'temperature.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11temperature.proto\"\x08\n\x06\x45mptyT\"*\n\x13TemperatureResponse\x12\x13\n\x0btemperature\x18\x01 \x01(\x02\x32\x45\n\x12TemperatureService\x12/\n\x0eGetTemperature\x12\x07.EmptyT\x1a\x14.TemperatureResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'temperature_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTYT']._serialized_start=21
  _globals['_EMPTYT']._serialized_end=29
  _globals['_TEMPERATURERESPONSE']._serialized_start=31
  _globals['_TEMPERATURERESPONSE']._serialized_end=73
  _globals['_TEMPERATURESERVICE']._serialized_start=75
  _globals['_TEMPERATURESERVICE']._serialized_end=144
# @@protoc_insertion_point(module_scope)
