# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chat.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'chat.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nchat.proto\"4\n\x07Message\x12\x0c\n\x04time\x18\x01 \x01(\t\x12\x0e\n\x06sender\x18\x02 \x01(\t\x12\x0b\n\x03msg\x18\x03 \x01(\t\"\t\n\x07NullMsg2^\n\x0f\x43hattingService\x12&\n\x0eGetInformation\x12\x08.NullMsg\x1a\x08.Message\"\x00\x12#\n\x0bSendMessage\x12\x08.Message\x1a\x08.NullMsg\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MESSAGE']._serialized_start=14
  _globals['_MESSAGE']._serialized_end=66
  _globals['_NULLMSG']._serialized_start=68
  _globals['_NULLMSG']._serialized_end=77
  _globals['_CHATTINGSERVICE']._serialized_start=79
  _globals['_CHATTINGSERVICE']._serialized_end=173
# @@protoc_insertion_point(module_scope)
